### ISSUE TITLE
steps not correct in v5

### ISSUE THREAD

**Issue by stereonom** [soyuka/dpicker#36]
Hi.
I tried this in your demo:
When u set min to "May 23, 2017 1:59:00 PM" , step=30 and now want to select the "May 23, 2017 2:00:00 PM" the options for the day include 13:00 and 13:30. 
When you trie to select them strange things happen.
14:00 gets the only option afterwards, and in my own case only :30 times are in the select-field. (step still 30)

Can you have a look?

**Comment by soyuka** [comment]
#35 gimme 10 min

**Comment by soyuka** [comment]
I bumped the docs/demo, should work better now! Note that every bug we already fixed (and I added a test case for each of those) remained intact during 4 => 5. Let me know if you find any :heart:!

**Comment by stereonom** [comment]
![may-24-2017 08-41-39](https://cloud.githubusercontent.com/assets/883533/26389980/d59e0c68-405c-11e7-94d0-76c17ee5f70e.gif)
still broken

**Comment by stereonom** [comment]
still broken
![adasdasdasd](https://cloud.githubusercontent.com/assets/883533/26390089/4e5a134a-405d-11e7-822d-6b1f5c4c4a51.gif)

**Comment by soyuka** [comment]
I made an attempt but I broke #11 :|. I think that I need to refactor this step thing...

**Comment by soyuka** [comment]
Quick bump on this I think that my fix does work fine on the #11 issue. Would you mind checking that it's okay now? Tyvm!

**Comment by stereonom** [comment]
where? it's not in the master or the develop-branch.

**Comment by soyuka** [comment]
I updated the docs (based on master) [commit](https://github.com/soyuka/dpicker/commit/e81fe1fbd097b6058e0d53927e7bd29a71b50d9d). I can't reproduce the above bug anymore. It is also a better fix for #11!

**Comment by stereonom** [comment]
yeah, i also can't reproduce it in the demo anymore.
would u mind sending me a build so I can test it in my app before you make a new official release?

**Comment by soyuka** [comment]
sure thing: [dpicker.zip](https://github.com/soyuka/dpicker/files/1036224/dpicker.zip)

If you want to build:

``` 
git clone git@github.com:soyuka/dpicker
cd dpicker
npm install
npm run build

# or `npm run build prod` to get minified versions
```

**Comment by stereonom** [comment]
min: 18:29, step 30. => no 18:30 in the selection
![image](https://cloud.githubusercontent.com/assets/883533/26557615/0fe8da16-44a3-11e7-95e8-e73be932c212.png)

min: 18:29, step 30. => no 18:30 in the selection
![image](https://cloud.githubusercontent.com/assets/883533/26557595/df593b70-44a2-11e7-96d1-d2cfcc560090.png)

**Comment by stereonom** [comment]
same with 18:15.
it shows the 18:XX steps when min = 18:00 or before.

**Comment by soyuka** [comment]
Okay, so step was parsed as a string, therefore the computation `minutes + step` was wrong... 
I also fixed the bug where hours and minutes were not being filtered according to min/max when concatenated. 

I bumped the demo with my last patch if you want to try.

**Comment by soyuka** [comment]
Hmm, still an issue when min and model have the same hour.

**Comment by soyuka** [comment]
:tada:

**Comment by stereonom** [comment]
fixed all my issues 💋

**Comment by soyuka** [comment]
landed in 5.0.5 :)

**Comment by stereonom** [comment]
Sorry, I have to reopen it.

`step`: `30`
`min`: `May 15, 2017 11:00:00 AM`
`max`: `July 11, 2017 11:30:00 AM`

select a date between these two dates. 
now change `min` to: `May 15, 2017 11:30:00 AM`

The option for `11:00` is now gone in the select field for every day between `min` and `max`

**Comment by soyuka** [comment]
My bad, forgot to add the sameDay check when `concatMinutesAndHours` is true. Patched and tested in https://github.com/soyuka/dpicker/commit/891169b207927aed00f5d505d2ea572ea9d2080f
